/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.suetholz.messageing.gui;

import net.suetholz.messageing.MessageStorageModel;
import net.suetholz.messageing.api.MessageStorage;

/**
 *
 * @author wsuetholz
 */
public class MessageStoragePanel extends javax.swing.JPanel {

    private MessageStorage messageStorage;
    
    /**
     * Creates new form MessageStoragePanel
     */
    public MessageStoragePanel(MessageStorage messageStorage) {
	if (messageStorage == null) {
	    throw new IllegalArgumentException();
	}
	
	this.messageStorage = messageStorage;
	
	initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblMessages = new javax.swing.JTable();

        setAutoscrolls(true);

        tblMessages.setModel(messageStorage.getTableModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(tblMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable tblMessages;
    // End of variables declaration//GEN-END:variables
}
