/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.suetholz.messageing.gui;

import java.util.List;
import net.suetholz.messageing.StringMessage;
import net.suetholz.messageing.api.MessageProducer;
import net.suetholz.messageing.api.MessageStorageChangedListener;
import net.suetholz.messageing.api.MessageType;

/**
 *
 * @author wsuetholz
 */
public class StringMessagePanel extends javax.swing.JPanel implements MessageProducer {
    private static final String LISTENER_NULL = "Initial Listeners is NULL!";

    List<MessageStorageChangedListener> initialListeners;

    /**
     * Creates new form StringMessagePanel
     */
    public StringMessagePanel(List<MessageStorageChangedListener> initialListeners) {
	if (initialListeners == null) {
	    throw new IllegalArgumentException(LISTENER_NULL);
	}

	this.initialListeners = initialListeners;
	initComponents();
    }

    @Override
    public final MessageType produceMessage() {
	return (new StringMessage (txtMessage.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        btnAddMessage = new javax.swing.JButton();
        btnRemoveMessage = new javax.swing.JButton();
        pneMessage = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();

        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMessage.setText("Message");

        btnAddMessage.addActionListener(new AddMessageListener(initialListeners));
        btnAddMessage.setText("Add Message");

        btnRemoveMessage.addActionListener(new RemoveMessageListener(initialListeners));
        btnRemoveMessage.setText("Remove Message");

        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        pneMessage.setViewportView(txtMessage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnAddMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoveMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pneMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMessage)
                    .addComponent(pneMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMessage)
                    .addComponent(btnRemoveMessage))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMessage;
    private javax.swing.JButton btnRemoveMessage;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JScrollPane pneMessage;
    private javax.swing.JTextArea txtMessage;
    // End of variables declaration//GEN-END:variables
}
